#!/usr/bin/env perl
use FindBin qw/ $Bin /;
use lib "$Bin/../lib"; # FIXME
use strict;
use warnings;
use AnyEvent;
use Log::Stash;

my $self = Log::Stash->new_with_options;
my $out = $self->output->new;
my $in = $self->input->new(output_to => $out);

AnyEvent->condvar->recv;

