#!/usr/bin/env perl
use FindBin qw/ $Bin /;
use lib "$Bin/../lib"; # FIXME
use strict;
use warnings;
use AnyEvent;
use Log::Stash;

my $self = Log::Stash->new_with_options;
$self->start;

AnyEvent->condvar->recv;

