=head1 NAME

Log::Stash::Manual - table of contents for Log::Stash documentation

=head1 CONTENTS

=over

=item L<Log::Stash::Manual::Concepts>

How (and why) logstash works.

=item L<Log::Stash::Manual::Cookbook>

Practical examplesof things you can do with the framework.

=item L<Log::Stash::Manual::Components>

Writing your own inputs, filters and outputs.

=back

=head1 AUTHOR & COPYRIGHT

See L<Log::Stash>.

=cut

